Adding Build state
blaquenkot/dungeon-builder pull request #4
Opened 2017-11-04 21:36 UTC by Kotzi

Bueno, era hora de hacer un PR.

Hay mucho que emprolijar pero me gustaría que lo vayas viendo, ya que por ahora es funcional.
Tengo dos cosas que me gustaría hacer después de esto:

1) Encapsular los tipos de bloque. Quedó todo bastante desprolijo eso. No sé si pueda reutilizar los modelos que se levantan para el juego en sí, pero es una opción a explorar.

2) Hacer el EXPORTADOR DE NIVELES para poder sacar un JSON con el nivel y pasárselo al PlayState.

Voy a agregar estas cosas a Trello así no se pierden.

2017-11-04 23:43 UTC, julioolvr requested changes

2017-11-04 23:43 UTC, julioolvr commented on src/js/states/build.js
> +    console.log(this.currentTile);
⚠️

2017-11-04 23:43 UTC, julioolvr commented on src/js/states/build.js
> +      this.game.math.snapToFloor(pointer.x, 32) / 32 +
Fijate que hay un `Level.GRID_SIZE` en `models/Level`, sería el mismo concepto que acá, ¿no?

2017-11-04 23:43 UTC, julioolvr commented on src/js/states/build.js
> +    this.layer = this.map.create('level1', 40, 30, 32, 32);
Este 40x30 se podría extraer a constantes de `Level` también

2017-11-04 23:45 UTC, julioolvr commented
Estaba pensando que el tamaño de este state tendría que ser un poco más grande para que entre el tile selector + un nivel entero, pero no sé si está bueno que cambie de tamaño el «juego» cuando pasás de build a play, así que quizás donde está el tile selector ahora sería un buen lugar para puntos/stats/menúes cuando estás jugando. No sé, habría que buscarle la vuelta (para no tener que hacer un tile selector flotante de momento).

2017-11-05 00:22 UTC, Kotzi commented on src/js/states/build.js
> +    this.layer = this.map.create('level1', 40, 30, 32, 32);
Yep 👍

2017-11-05 00:22 UTC, Kotzi commented on src/js/states/build.js
> +      this.game.math.snapToFloor(pointer.x, 32) / 32 +
Sí, me olvidé completamente de esas constantes.

2017-11-05 00:22 UTC, Kotzi commented on src/js/states/build.js
> +    console.log(this.currentTile);
Ya lo saco 🙌

2017-11-05 00:27 UTC, Kotzi commented
Sí, creo que modificar el tamaño del Game sería medio choto por lo pronto. Creo que tenemos que aprovechar a usarlo como HUD.
Lo que podemos pensar eventualmente es agrupar los sprites de otra forma para hacerlo menos alto (de la nada, se me ocurre usar izquierda y derecha para cosas diferentes, entonces metemos bloques a izquierda y spikes a derecha en la primera línea y, en la segunda, player y flag).

2017-11-05 00:32 UTC, julioolvr commented
Se, habría que ver la doc de Phaser a ver cuál sería la mejor manera de extraer esa toolbox por separado, cosa de poder meter lógica más complicada para las coordenadas de cada elemento y eso sin que el build state sea un quilombo.

2017-11-05 00:34 UTC, Kotzi commented
Eso me gusta. Veamos qué onda con la componetización en los examples (miedo).

2017-11-07 18:14 UTC, julioolvr approved these changes
Sacale el `console.log` ese y mergealo 🙌

2017-11-07 18:14 UTC, julioolvr commented on src/js/states/build.js
> +      console.log(this.points);
🤔

2017-11-07 18:20 UTC, Kotzi commented on src/js/states/build.js
> +      console.log(this.points);
Este pobre console.log es nuestro printeador de niveles, es lo mejor que teníamos :P

2017-11-07 18:21 UTC, merged

2017-11-07 18:27 UTC, julioolvr commented on src/js/states/build.js
> +      console.log(this.points);
Ahh boludo, pensé que había quedado colgado nomás :P Bueno, después si nos sirve lo volvemos a agregar jaja

2017-11-07 18:28 UTC, Kotzi commented on src/js/states/build.js
> +      console.log(this.points);
Jaja, no te preocupes, mi próximo PR debería tener la magia que genere el nivel y lo pueda levantar alguien más (?)